schema_version = "1.0.0"

id = "only_blends_core"
version = "0.5.1"
name = "OnlyBlends.Core"
tagline = "1-Node Editor from scratch 2-Spawn Objects from Geo Modifiers"
maintainer = "Zulhakar (ChangeGamer) <Ilineiros@proton.me>"
type = "add-on"
website = "https://github.com/Zulhakar/OnlyBlendsCore"
tags = ["Node"]
blender_version_min = "4.2.0"
license = [
    "SPDX:GPL-3.0-or-later",
]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  ".*",
  "*.zip",
    ".idea",
    "*.blend",
  "test"
]